name: CI/CD to AKS

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    # ğŸ”‘ Login to Azure
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # ğŸ³ Build & Push Docker image to ACR
    - name: Build and Push Image
      uses: docker/build-push-action@v5
      with:

        file: Dockerfile
        push: true
        tags: sysopex123.azurecr.io/sysopexapp:v1


    # ğŸ”‘ Set AKS credentials
    - name: Get AKS Credentials
      run: |
        az aks get-credentials \
          --resource-group SysOpsEX\
          --name SysOpsEx-aks \
          --overwrite-existing



    # ğŸš€ Deploy App + Service + PodDisruptionBudget
    - name: Deploy Application
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        

#    # âœ… Verify rollout
#    - name: Verify App Rollout
#      run: |
#        kubectl rollout status deployment/my-app -n default
